services:
  migrate:
    image: heatroute-api
  api:
    image: heatroute-api
  worker:
    image: heatroute-worker
  scheduler:
    image: heatroute-scheduler
  web:
    image: heatroute-web

networks:
  default:
    internal: true
